services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${SERVICE_NAME}
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PUID: $PUID
      PGID: $PGID # grep docker /etc/group
      HOMEPAGE_VAR_DOMAIN: ${HOMEPAGE_VAR_DOMAIN}
      HOMEPAGE_VAR_UNIFI_USER: ${HOMEPAGE_VAR_UNIFI_USER}
      HOMEPAGE_VAR_UNIFI_PASS: ${HOMEPAGE_VAR_UNIFI_PASS}
      HOMEPAGE_VAR_PIHOLE_KEY: ${HOMEPAGE_VAR_PIHOLE_KEY}
      HOMEPAGE_VAR_OFFSITE_NAS: ${HOMEPAGE_VAR_OFFSITE_NAS}
      HOMEPAGE_VAR_PROXMOX_API_USER: ${HOMEPAGE_VAR_PROXMOX_API_USER}
      HOMEPAGE_VAR_PROXMOX_API_KEY: ${HOMEPAGE_VAR_PROXMOX_API_KEY}
    dns:
      - '${DNS_SERVER}'
    networks:
      - proxy
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=http"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${HOMEPAGE_VAR_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.${SERVICE_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-https-redirect"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${SERVICE_NAME}.${HOMEPAGE_VAR_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.service=${SERVICE_NAME}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_INTERNAL_PORT}"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
  external:
    external: true
