---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- HomeLab:
    - My GitHub Repos:
        - href: https://github.com/devopsleigh?tab=repositories
    - My GitHub Gists:
        - href: https://gist.github.com/devopsleigh
    - Cloudflare:
        - href: https://dash.cloudflare.com
    - Proxmox Helper Scripts:
       - href: https://helper-scripts.com/scripts

- Reference:
    - Copilot:
      - href: https://copilot.microsoft.com
    - YouTube:
        - href: https://youtube.com/
