---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- HomeLab:
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com
    - GitHub:
        - abbr: GH
          href: https://github.com/devopsleigh
    - Proxmox Helper Scripts:
       - abbr: PH
         href: https://helper-scripts.com/scripts

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
