---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- HomeLab:
    - My GitHub Repos:
        - abbr: GR
          href: https://github.com/devopsleigh?tab=repositories
    - My GitHub Gists:
        - abbr: GG
          href: https://gist.github.com/devopsleigh
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com
    - Proxmox Helper Scripts:
       - abbr: PH
         href: https://helper-scripts.com/scripts

- Utilities:
    - Copilot:
      - abbr: CP
        href: https://copilot.microsoft.com

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
