---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# For icons, see:
# https://github.com/walkxcode/dashboard-icons/tree/main/svg

# Technical Services

- Networking:
    - UniFi Controller:
        href: https://192.168.1.1
        description: UniFi network management
        icon: unifi
        # widget:
        #   type: unifi
        #   url: https://192.168.1.1
        #   username: {{HOMEPAGE_VAR_UNIFI_USER}}
        #   password: {{HOMEPAGE_VAR_UNIFI_PASS}}
    - Pi-hole 1:
        href: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052/admin
        description: Network-wide ad blocker and local DNS
        icon: pi-hole
        siteMonitor: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052/admin
        widget:
          type: pihole
          url: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Pi-hole 2:
        href: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}/admin
        description: Network-wide ad blocker and local DNS
        icon: pi-hole
        siteMonitor: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}/admin
        widget:
          type: pihole
          url: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}

- Hosting:
    - Proxmox Cluster:
        href: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
        description: Hypervisor
        icon: proxmox
        siteMonitor: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
        widget:
            type: proxmox
            url: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_API_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
    # - Proxmox 2:
    #     href: https://pve-02.{{HOMEPAGE_VAR_DOMAIN}}:8006
    #     description: Hypervisor
    #     icon: proxmox
    #     siteMonitor: https://pve-02.{{HOMEPAGE_VAR_DOMAIN}}:8006
    #     # widget:
    #     #     type: proxmox
    #     #     url: https://pve-02.{{HOMEPAGE_VAR_DOMAIN}}:8006
    #     #     username: {{HOMEPAGE_VAR_PROXMOX_API_USER}}
    #     #     password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
    #         # node: pve-02
    # - Proxmox 3:
    #     href: https://pve-03.{{HOMEPAGE_VAR_DOMAIN}}:8006
    #     description: Hypervisor
    #     icon: proxmox
    #     siteMonitor: https://pve-03.{{HOMEPAGE_VAR_DOMAIN}}:8006
    #     # widget:
    #     #     type: proxmox
    #     #     url: https://pve-03.{{HOMEPAGE_VAR_DOMAIN}}:8006
    #     #     username: {{HOMEPAGE_VAR_PROXMOX_API_USER}}
    #     #     password: {{HOMEPAGE_VAR_PROXMOX_API_KEY}}
    #         # node: pve-03
    - Proxmox Backup Server:
        href: https://pbs.{{HOMEPAGE_VAR_DOMAIN}}:8007
        description: Backup manager for Proxmox
        icon: proxmox-light.png
        siteMonitor: https://pbs.{{HOMEPAGE_VAR_DOMAIN}}:8007
    - Synology DSM:
        href: https://nas.{{HOMEPAGE_VAR_DOMAIN}}
        description: Network-attached storage
        icon: synology-dsm
        siteMonitor: https://nas.{{HOMEPAGE_VAR_DOMAIN}}
    - Offsite NAS:
          href: {{HOMEPAGE_VAR_OFFSITE_NAS}}
          description: Off-site NAS for critical backup
          icon: synology-dsm
          siteMonitor: {{HOMEPAGE_VAR_OFFSITE_NAS}}

# - Security and Monitoring:

# - Development and Automation:

# User Services

# - Utilities:

- Entertainment:
    - Plex:
        href: http://plex.{{HOMEPAGE_VAR_DOMAIN}}:32400/web
        description: Local media streaming service
        icon: plex
        siteMonitor: http://plex.{{HOMEPAGE_VAR_DOMAIN}}:32400
    - Jellyfin:
        href: https://jellyfin.{{HOMEPAGE_VAR_DOMAIN}}
        description: Local media streaming service (works without internet)
        icon: jellyfin
        siteMonitor: https://jellyfin.{{HOMEPAGE_VAR_DOMAIN}}
    - MeTube:
        href: https://metube.elnet.xyz
        description: YouTube video downloader
        icon: metube
        siteMonitor: https://metube.elnet.xyz

- Home:
    - Home Assistant:
        href: https://homeassistant.{{HOMEPAGE_VAR_DOMAIN}}
        description: Home automation platform
        icon: home-assistant
        siteMonitor: https://homeassistant.{{HOMEPAGE_VAR_DOMAIN}}
    - CCTV:
        href: https://nvr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Security cameras
        icon: mdi-cctv
        siteMonitor: https://nvr.{{HOMEPAGE_VAR_DOMAIN}}
