---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network:
    - UniFi Controller:
        href: https://192.168.1.1
        description: Network management software for Ubiquiti devices
        icon: unifi
        widget:
          type: unifi
          url: https://192.168.1.1
          username: {{HOMEPAGE_VAR_UNIFI_USER}}
          password: {{HOMEPAGE_VAR_UNIFI_PASS}}
    - Pi-hole 01:
        href: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052/admin
        description: Network-wide ad blocker and local DNS
        icon: pi-hole
        ping: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052/admin
        widget:
          type: pihole
          url: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Pi-hole 02:
        href: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}/admin
        description: Network-wide ad blocker and local DNS
        icon: pi-hole
        ping: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}/admin
        widget:
          type: pihole
          url: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}

- Hosting:
    - Proxmox:
        href: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
        description: Hypervisor
        icon: proxmox
#        widget:
#          type: proxmox
#          url: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
#          username: api_token_id
#          password: api_token_secret
    - Synology NAS:
        href: https://nas.{{HOMEPAGE_VAR_DOMAIN}}:5001
        description: Network-attached storage system
        icon: synology-dsm
        ping: https://nas.{{HOMEPAGE_VAR_DOMAIN}}:5001
#        widget:
#          type: diskstation
#          url: https://nas.{{HOMEPAGE_VAR_DOMAIN}}:5001
#          username: username
#          password: password
    - Nginx Proxy Manager:
        href: https://proxy.{{HOMEPAGE_VAR_DOMAIN}}
        description: TLS front end and reverse proxy
        icon: nginx-proxy-manager
        ping: https://proxy.{{HOMEPAGE_VAR_DOMAIN}}

- Security:
    - Keycloak:
        href: https://keycloak.{{HOMEPAGE_VAR_DOMAIN}}
        description: Single sign-on authentication server
        icon: keycloak
        ping: https://keycloak.{{HOMEPAGE_VAR_DOMAIN}}
    - Wazuh:
        href: https://wazuh.{{HOMEPAGE_VAR_DOMAIN}}
        description: Security monitoring and intrusion detection
        icon: https://avatars.githubusercontent.com/u/13752566
        ping: https://wazuh.{{HOMEPAGE_VAR_DOMAIN}}
    - The Hive:
        href: https://hive.{{HOMEPAGE_VAR_DOMAIN}}
        description: Incident response and case management
        icon: https://www.strangebee.com/images/logos/bee-white.svg
        ping: https://hive.{{HOMEPAGE_VAR_DOMAIN}}
    - Pi-Alert:
        href: http://pialert.{{HOMEPAGE_VAR_DOMAIN}}
        description: Network monitoring tool for detecting rogue devices
        icon: mdi-server-security
        ping: http://pialert.{{HOMEPAGE_VAR_DOMAIN}}

- Home Automation:
    - Home Assistant:
        href: http://ha.{{HOMEPAGE_VAR_DOMAIN}}
        description: Home automation platform
        icon: home-assistant
        ping: http://ha.{{HOMEPAGE_VAR_DOMAIN}}
#        widget:
#          type: homeassistant
#          url: http://homeassistant.host.or.ip:port
#          key: access_token
    - NodeRed:
        href: https://nodered.{{HOMEPAGE_VAR_DOMAIN}}
        description: Flow-based development tool for IoT applications
        icon: node-red
        ping: https://nodered.{{HOMEPAGE_VAR_DOMAIN}}

- Development:
    - GitLab:
        href: https://gitlab.{{HOMEPAGE_VAR_DOMAIN}}
        description: Version control and CI/CD platform
        icon: gitlab
        ping: https://gitlab.{{HOMEPAGE_VAR_DOMAIN}}

- Services:
    - Paperless:
        href: http://docs.{{HOMEPAGE_VAR_DOMAIN}}
        description: Document management system
        icon: paperless-ngx
        ping: http://docs.{{HOMEPAGE_VAR_DOMAIN}}
    - Mealie:
        href: http://mealie.{{HOMEPAGE_VAR_DOMAIN}}
        description: Recipe management and meal planning
        icon: mealie
        ping: http://mealie.{{HOMEPAGE_VAR_DOMAIN}}
    - Plex:
        href: https://plex.{{HOMEPAGE_VAR_DOMAIN}}:32400/web
        description: Home media streaming service
        icon: plex
        ping: https://plex.{{HOMEPAGE_VAR_DOMAIN}}
    - Makemkv:
        href: https://makemkv.{{HOMEPAGE_VAR_DOMAIN}}
        description: DVD and Blu-Ray backup and conversion
        icon: makemkv.png
        ping: https://makemkv.{{HOMEPAGE_VAR_DOMAIN}}
    - Kiwix:
        href: http://kiwix.{{HOMEPAGE_VAR_DOMAIN}}
        description: Offline Wiki reader
        icon: kiwix
        ping: http://kiwix.{{HOMEPAGE_VAR_DOMAIN}}
