---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

# Technical Services

- Network:
    - UniFi Controller:
        href: https://192.168.1.1
        description: UniFi network management
        icon: unifi
        widget:
          type: unifi
          url: https://192.168.1.1
          username: {{HOMEPAGE_VAR_UNIFI_USER}}
          password: {{HOMEPAGE_VAR_UNIFI_PASS}}
    - Pi-hole 01:
        href: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052/admin
        description: Network-wide ad blocker and local DNS
        icon: pi-hole
        ping: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052/admin
        widget:
          type: pihole
          url: http://pihole-01.{{HOMEPAGE_VAR_DOMAIN}}:2052
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Pi-hole 02:
        href: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}/admin
        description: Network-wide ad blocker and local DNS
        icon: pi-hole
        ping: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}/admin
        widget:
          type: pihole
          url: http://pihole-02.{{HOMEPAGE_VAR_DOMAIN}}
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - NetAlertX:
        href: https://netalertx.{{HOMEPAGE_VAR_DOMAIN}}
        description: Network monitoring tool for detecting rogue devices
        icon: pi-alert.png
        ping: http://netalertx.{{HOMEPAGE_VAR_DOMAIN}}

- Hosting:
    - Proxmox:
        href: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
        description: Hypervisor
        icon: proxmox
        ping: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
#        widget:
#          type: proxmox
#          url: https://pve-01.{{HOMEPAGE_VAR_DOMAIN}}:8006
#          username: api_token_id
#          password: api_token_secret
    - Synology NAS:
        href: https://nas.{{HOMEPAGE_VAR_DOMAIN}}:5001
        description: Network-attached storage
        icon: synology-dsm
        ping: https://nas.{{HOMEPAGE_VAR_DOMAIN}}:5001
#        widget:
#          type: diskstation
#          url: https://nas.{{HOMEPAGE_VAR_DOMAIN}}:5001
#          username: username
#          password: password
    - Traefik:
        href: https://traefik.{{HOMEPAGE_VAR_DOMAIN}}
        description: TLS front end and reverse proxy
        icon: traefik
        ping: https://traefik.{{HOMEPAGE_VAR_DOMAIN}}
    - Uptime Kuma:
        href: https://uptimekuma.{{HOMEPAGE_VAR_DOMAIN}}
        description: Service monitoring
        icon: uptime-kuma
        ping: https://uptimekuma.{{HOMEPAGE_VAR_DOMAIN}}
    - Kasm:
        href: https://kasm.{{HOMEPAGE_VAR_DOMAIN}}
        description: Desktop as a Service
        icon: kasm
        ping: https://kasm.{{HOMEPAGE_VAR_DOMAIN}}

- Security:
    - Keycloak:
        href: https://keycloak.{{HOMEPAGE_VAR_DOMAIN}}
        description: Single sign-on authentication
        icon: keycloak
        ping: https://keycloak.{{HOMEPAGE_VAR_DOMAIN}}
    - Wazuh:
        href: https://wazuh.{{HOMEPAGE_VAR_DOMAIN}}
        description: Security monitoring and intrusion detection
        icon: https://avatars.githubusercontent.com/u/13752566
        ping: https://wazuh.{{HOMEPAGE_VAR_DOMAIN}}
    - The Hive:
        href: https://hive.{{HOMEPAGE_VAR_DOMAIN}}
        description: Incident response and case management
        icon: https://www.strangebee.com/images/logos/bee-white.svg
        ping: https://hive.{{HOMEPAGE_VAR_DOMAIN}}
    - Caldera:
        href: https://caldera.{{HOMEPAGE_VAR_DOMAIN}}
        description: Adversary emulation
        icon: caldera.png
        ping: https://caldera.{{HOMEPAGE_VAR_DOMAIN}}

- Home Automation:
    - Home Assistant:
        href: https://homeassistant.{{HOMEPAGE_VAR_DOMAIN}}
        description: Home automation platform
        icon: home-assistant
        ping: https://homeassistant.{{HOMEPAGE_VAR_DOMAIN}}
#        widget:
#          type: homeassistant
#          url: http://homeassistant.host.or.ip:port
#          key: access_token
    - NodeRed:
        href: https://nodered.{{HOMEPAGE_VAR_DOMAIN}}
        description: Flow-based automations
        icon: node-red
        ping: https://nodered.{{HOMEPAGE_VAR_DOMAIN}}

- Development:
    - GitLab:
        href: https://gitlab.{{HOMEPAGE_VAR_DOMAIN}}
        description: Version control and CI/CD
        icon: gitlab
        ping: https://gitlab.{{HOMEPAGE_VAR_DOMAIN}}
    - SonarQube:
        href: https://sonarqube.{{HOMEPAGE_VAR_DOMAIN}}
        description: Static code analysis and quality scanning
        icon: si-sonarqube
        ping: https://sonarqube.{{HOMEPAGE_VAR_DOMAIN}}

# User Services

- Utilities:
    - Paperless:
        href: https://paperless.{{HOMEPAGE_VAR_DOMAIN}}
        description: Document management
        icon: paperless-ngx
        ping: https://paperless.{{HOMEPAGE_VAR_DOMAIN}}
    - Mealie:
        href: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
        description: Recipe management and meal planning
        icon: mealie
        ping: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
    - Kiwix:
        href: https://kiwix.{{HOMEPAGE_VAR_DOMAIN}}
        description: Offline Wiki reader
        icon: kiwix
        ping: https://kiwix.{{HOMEPAGE_VAR_DOMAIN}}
- Entertainment:
    - Plex:
        href: http://plex.{{HOMEPAGE_VAR_DOMAIN}}:32400/web
        description: Home media streaming service
        icon: plex
        ping: http://plex.{{HOMEPAGE_VAR_DOMAIN}}:32400
    - Makemkv:
        href: http://makemkv.{{HOMEPAGE_VAR_DOMAIN}}
        description: DVD and Blu-Ray backup and conversion
        icon: makemkv.png
        ping: http://makemkv.{{HOMEPAGE_VAR_DOMAIN}}
- Home:
    - Home Assistant:
        href: https://homeassistant.{{HOMEPAGE_VAR_DOMAIN}}
        description: Home automation platform
        icon: home-assistant
        ping: https://homeassistant.{{HOMEPAGE_VAR_DOMAIN}}
    - CCTV:
        href: http://nvr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Security cameras
        icon: mdi-cctv
        ping: http://nvr.{{HOMEPAGE_VAR_DOMAIN}}
