---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true

showStats: true
statusStyle: "dot"
theme: dark
color: slate

layout:
# User Services
  Home:
    tab: User Services
  Business:
    tab: User Services
  Entertainment:
    tab: User Services
  Utilities:
    tab: User Services
# Technical Services
  Network:
     tab: Technical Services
  Hosting:
     tab: Technical Services
  Security:
     tab: Technical Services
  Development:
     tab: Technical Services
  Home Automation:
     tab: Technical Services
  Developer:
     tab: Technical Services
