---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true

showStats: true

layout:
  Services:
    tab: User Services
  Network:
     tab: Technical Services
  Hosting:
     tab: Technical Services
  Security:
     tab: Technical Services
  Development:
     tab: Technical Services
  Home Automation:
     tab: Technical Services
  Developer:
     tab: Technical Services
